In [1]:
import numpy as np

# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Matrix addition
print("\nAddition of A and B:")
print(A + B)

# Matrix subtraction
print("\nSubtraction of A and B:")
print(A - B)

# Matrix multiplication
print("\nMatrix multiplication:")
print(np.dot(A, B))

# Transpose
print("\nTranspose of A:")
print(A.T)

# Determinant
print("\nDeterminant of A:")
print(np.linalg.det(A))

# Inverse
print("\nInverse of A:")
print(np.linalg.inv(A))

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Addition of A and B:
[[ 6  8]
 [10 12]]

Subtraction of A and B:
[[-4 -4]
 [-4 -4]]

Matrix multiplication:
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A:
-2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]
